2024-08-17 15:22:02,749 - INFO - ARIMA_Model instanciado.
2024-08-17 15:22:02,749 - INFO - Tamanho do conjunto de treino: 5256
2024-08-17 15:22:02,749 - INFO - Tamanho do conjunto de validação: 1752
2024-08-17 15:22:03,222 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:03,222 - INFO - ARIMA(p=1, d=1, q=1) - MSE: 0.1240, MAPE: inf
2024-08-17 15:22:04,265 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:04,265 - INFO - ARIMA(p=1, d=1, q=2) - MSE: 0.1127, MAPE: inf
2024-08-17 15:22:07,038 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:07,190 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:07,190 - INFO - ARIMA(p=1, d=1, q=3) - MSE: 0.0759, MAPE: inf
2024-08-17 15:22:10,164 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:10,327 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:10,327 - INFO - ARIMA(p=1, d=1, q=4) - MSE: 0.0761, MAPE: inf
2024-08-17 15:22:11,410 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:11,411 - INFO - ARIMA(p=2, d=1, q=1) - MSE: 0.1202, MAPE: inf
2024-08-17 15:22:13,621 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:13,622 - INFO - ARIMA(p=2, d=1, q=2) - MSE: 0.0759, MAPE: inf
2024-08-17 15:22:17,102 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:17,223 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:17,224 - INFO - ARIMA(p=2, d=1, q=3) - MSE: 0.0754, MAPE: inf
2024-08-17 15:22:20,773 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:20,916 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:20,916 - INFO - ARIMA(p=2, d=1, q=4) - MSE: 0.0756, MAPE: inf
2024-08-17 15:22:24,928 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:25,056 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:25,056 - INFO - ARIMA(p=3, d=1, q=1) - MSE: 0.0761, MAPE: inf
2024-08-17 15:22:25,059 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-17 15:22:25,059 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-17 15:22:27,904 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:28,015 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:28,015 - INFO - ARIMA(p=3, d=1, q=2) - MSE: 0.0761, MAPE: inf
2024-08-17 15:22:31,341 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:31,474 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:31,474 - INFO - ARIMA(p=3, d=1, q=3) - MSE: 0.0756, MAPE: inf
2024-08-17 15:22:36,658 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:36,842 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:36,843 - INFO - ARIMA(p=3, d=1, q=4) - MSE: 0.0757, MAPE: inf
2024-08-17 15:22:39,793 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:39,793 - INFO - ARIMA(p=4, d=1, q=1) - MSE: 0.0762, MAPE: inf
2024-08-17 15:22:39,796 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-17 15:22:39,797 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-17 15:22:43,304 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:43,459 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:43,459 - INFO - ARIMA(p=4, d=1, q=2) - MSE: 0.0762, MAPE: inf
2024-08-17 15:22:47,526 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:47,718 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:47,718 - INFO - ARIMA(p=4, d=1, q=3) - MSE: 0.0757, MAPE: inf
2024-08-17 15:22:52,094 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-17 15:22:52,271 - WARNING - divide by zero encountered in divide (Category: RuntimeWarning, File: /home/tathiana/PycharmProjects/conbrepro/arma_model.py, Line: 29)
2024-08-17 15:22:52,271 - INFO - ARIMA(p=4, d=1, q=4) - MSE: 0.0757, MAPE: inf
2024-08-17 15:22:52,271 - INFO - Melhor modelo: ARIMA(p=2, d=1, q=3) - MSE: 0.0754 - MAPE: inf
2024-08-19 11:09:40,850 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 11:09:40,863 - INFO - Dados de radiacao_global extraídos com sucesso.
2024-08-19 11:09:40,864 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5256, Validação: 1752, Teste: 1752.
2024-08-19 11:09:40,865 - INFO - Dados escalonados para o intervalo: (-1, 1).
2024-08-19 11:09:40,865 - INFO - ARIMA_Model instanciado.
2024-08-19 11:09:40,865 - INFO - Tamanho do conjunto de treino: 5256
2024-08-19 11:09:40,865 - INFO - Tamanho do conjunto de validação: 1752
2024-08-19 11:09:41,141 - INFO - ARIMA(p=1, d=1, q=1) - MSE: 2068077.8377
2024-08-19 11:09:41,554 - INFO - ARIMA(p=1, d=1, q=2) - MSE: 1879136.3910
2024-08-19 11:09:44,071 - INFO - ARIMA(p=1, d=1, q=3) - MSE: 1266353.4369
2024-08-19 11:09:47,210 - INFO - ARIMA(p=1, d=1, q=4) - MSE: 1266445.2623
2024-08-19 11:09:47,777 - INFO - ARIMA(p=2, d=1, q=1) - MSE: 2004096.0394
2024-08-19 11:09:50,170 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:09:50,277 - INFO - ARIMA(p=2, d=1, q=2) - MSE: 1251490.0359
2024-08-19 11:09:53,212 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:09:53,346 - INFO - ARIMA(p=2, d=1, q=3) - MSE: 1257103.8354
2024-08-19 11:09:56,667 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:09:56,807 - INFO - ARIMA(p=2, d=1, q=4) - MSE: 1259938.9314
2024-08-19 11:09:58,706 - INFO - ARIMA(p=3, d=1, q=1) - MSE: 1268207.8457
2024-08-19 11:09:58,709 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:09:58,709 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:10:01,563 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:10:01,684 - INFO - ARIMA(p=3, d=1, q=2) - MSE: 1258558.7328
2024-08-19 11:10:05,737 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:10:05,919 - INFO - ARIMA(p=3, d=1, q=3) - MSE: 1255464.3299
2024-08-19 11:10:11,050 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:10:11,205 - INFO - ARIMA(p=3, d=1, q=4) - MSE: 1257106.8632
2024-08-19 11:10:14,077 - INFO - ARIMA(p=4, d=1, q=1) - MSE: 1269132.4064
2024-08-19 11:10:14,080 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:10:14,081 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:10:18,282 - INFO - ARIMA(p=4, d=1, q=2) - MSE: 1268205.0347
2024-08-19 11:10:23,034 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:10:23,175 - INFO - ARIMA(p=4, d=1, q=3) - MSE: 1258549.5050
2024-08-19 11:10:29,027 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:10:29,219 - INFO - ARIMA(p=4, d=1, q=4) - MSE: 1260234.3959
2024-08-19 11:10:29,219 - INFO - Melhor modelo: ARIMA(p=4, d=1, q=1) - MSE: inf
2024-08-19 11:10:29,219 - ERROR - Erro no processo de modelagem: name 'residuals' is not defined
2024-08-19 11:10:42,047 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 11:20:46,101 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 11:20:46,117 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5256, Validação: 1752, Teste: 1752.
2024-08-19 11:21:26,582 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 11:21:29,232 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 11:22:03,913 - INFO - ARIMA_Model instanciado.
2024-08-19 11:22:20,660 - INFO - ARIMA_Model instanciado.
2024-08-19 11:22:21,602 - INFO - ARIMA_Model instanciado.
2024-08-19 11:22:32,037 - INFO - Tamanho do conjunto de treino: 5256
2024-08-19 11:22:32,037 - INFO - Tamanho do conjunto de validação: 1752
2024-08-19 11:22:32,038 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:32,040 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:32,043 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:32,492 - INFO - ARIMA(p=1, d=1, q=1) - MSE: 0.4960
2024-08-19 11:22:32,492 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:32,493 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:32,493 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:33,033 - INFO - ARIMA(p=1, d=1, q=2) - MSE: 0.4507
2024-08-19 11:22:33,033 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:33,034 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:33,034 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:36,200 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:22:36,353 - INFO - ARIMA(p=1, d=1, q=3) - MSE: 0.3037
2024-08-19 11:22:36,353 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:36,354 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:36,354 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:40,266 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:22:40,452 - INFO - ARIMA(p=1, d=1, q=4) - MSE: 0.3037
2024-08-19 11:22:40,453 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:40,453 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:40,454 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:41,151 - INFO - ARIMA(p=2, d=1, q=1) - MSE: 0.4806
2024-08-19 11:22:41,151 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:41,152 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:41,153 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:42,451 - INFO - ARIMA(p=2, d=1, q=2) - MSE: 0.3035
2024-08-19 11:22:42,452 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:42,452 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:42,453 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:45,627 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:22:45,756 - INFO - ARIMA(p=2, d=1, q=3) - MSE: 0.3014
2024-08-19 11:22:45,756 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:45,757 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:45,757 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:49,338 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:22:49,486 - INFO - ARIMA(p=2, d=1, q=4) - MSE: 0.3020
2024-08-19 11:22:49,486 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:49,486 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:49,487 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:51,890 - INFO - ARIMA(p=3, d=1, q=1) - MSE: 0.3044
2024-08-19 11:22:51,890 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:51,891 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:51,892 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:51,894 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:22:51,894 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:22:54,756 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:22:54,871 - INFO - ARIMA(p=3, d=1, q=2) - MSE: 0.3089
2024-08-19 11:22:54,871 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:54,872 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:54,873 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:58,804 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:22:58,939 - INFO - ARIMA(p=3, d=1, q=3) - MSE: 0.3022
2024-08-19 11:22:58,940 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:58,940 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:22:58,941 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:03,579 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:23:03,734 - INFO - ARIMA(p=3, d=1, q=4) - MSE: 0.3017
2024-08-19 11:23:03,734 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:03,734 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:03,735 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:06,844 - INFO - ARIMA(p=4, d=1, q=1) - MSE: 0.3048
2024-08-19 11:23:06,844 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:06,845 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:06,846 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:06,848 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:23:06,848 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:23:10,778 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:23:10,946 - INFO - ARIMA(p=4, d=1, q=2) - MSE: 0.3048
2024-08-19 11:23:10,946 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:10,947 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:10,948 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:15,571 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:23:15,767 - INFO - ARIMA(p=4, d=1, q=3) - MSE: 0.3021
2024-08-19 11:23:15,767 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:15,768 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:15,768 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:23:20,023 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:23:20,185 - INFO - ARIMA(p=4, d=1, q=4) - MSE: 0.3020
2024-08-19 11:23:20,185 - INFO - Melhor modelo: ARIMA(p=4, d=1, q=1) - MSE: inf
2024-08-19 11:38:18,407 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 11:38:18,427 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5256, Validação: 1752, Teste: 1752.
2024-08-19 11:38:18,434 - INFO - Dados escalonados para o intervalo: (-1, 1).
2024-08-19 11:38:18,434 - INFO - ARIMA_Model instanciado.
2024-08-19 11:38:22,377 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:22,380 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:22,382 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:22,822 - ERROR - Erro ao ajustar o modelo ARIMA(p=1, d=1, q=1): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index, end=y_train_len + val_size - 1)
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:38:22,829 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:22,829 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:22,830 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:23,363 - ERROR - Erro ao ajustar o modelo ARIMA(p=1, d=1, q=2): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index, end=y_train_len + val_size - 1)
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:38:23,370 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:23,370 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:23,372 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:26,642 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:38:26,771 - ERROR - Erro ao ajustar o modelo ARIMA(p=1, d=1, q=3): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index, end=y_train_len + val_size - 1)
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:38:26,780 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:26,781 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:26,782 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:41,077 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 11:38:41,097 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5256, Validação: 1752, Teste: 1752.
2024-08-19 11:38:41,104 - INFO - Dados escalonados para o intervalo: (-1, 1).
2024-08-19 11:38:41,104 - INFO - ARIMA_Model instanciado.
2024-08-19 11:38:55,254 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:55,256 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:38:55,257 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:02,353 - ERROR - Erro ao ajustar o modelo ARIMA(p=1, d=1, q=1): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:02,359 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:02,361 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:02,363 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:02,937 - ERROR - Erro ao ajustar o modelo ARIMA(p=1, d=1, q=2): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:02,940 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:02,940 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:02,941 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:06,158 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:06,283 - ERROR - Erro ao ajustar o modelo ARIMA(p=1, d=1, q=3): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:06,286 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:06,287 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:06,288 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:10,234 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:10,391 - ERROR - Erro ao ajustar o modelo ARIMA(p=1, d=1, q=4): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:10,393 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:10,394 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:10,395 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:11,075 - ERROR - Erro ao ajustar o modelo ARIMA(p=2, d=1, q=1): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:11,079 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:11,080 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:11,080 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:12,372 - ERROR - Erro ao ajustar o modelo ARIMA(p=2, d=1, q=2): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:12,375 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:12,375 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:12,376 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:15,565 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:15,659 - ERROR - Erro ao ajustar o modelo ARIMA(p=2, d=1, q=3): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:15,662 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:15,662 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:15,663 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:19,294 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:19,407 - ERROR - Erro ao ajustar o modelo ARIMA(p=2, d=1, q=4): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:19,410 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:19,410 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:19,411 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:21,801 - ERROR - Erro ao ajustar o modelo ARIMA(p=3, d=1, q=1): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:21,804 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:21,804 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:21,805 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:21,808 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:41:21,808 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:41:24,702 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:24,791 - ERROR - Erro ao ajustar o modelo ARIMA(p=3, d=1, q=2): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:24,794 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:24,795 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:24,795 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:28,778 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:28,882 - ERROR - Erro ao ajustar o modelo ARIMA(p=3, d=1, q=3): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:28,885 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:28,886 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:28,887 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:33,540 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:33,666 - ERROR - Erro ao ajustar o modelo ARIMA(p=3, d=1, q=4): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:33,669 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:33,670 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:33,670 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:36,793 - ERROR - Erro ao ajustar o modelo ARIMA(p=4, d=1, q=1): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:36,796 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:36,797 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:36,797 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:36,800 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:41:36,800 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:41:40,761 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:40,900 - ERROR - Erro ao ajustar o modelo ARIMA(p=4, d=1, q=2): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:40,903 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:40,904 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:40,904 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:45,598 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:45,765 - ERROR - Erro ao ajustar o modelo ARIMA(p=4, d=1, q=3): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:41:45,768 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:45,769 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:45,769 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:41:50,131 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:41:50,263 - ERROR - Erro ao ajustar o modelo ARIMA(p=4, d=1, q=4): name 'y_train_len' is not defined
Traceback (most recent call last):
  File "/home/tathiana/PycharmProjects/conbrepro/arima_model.py", line 46, in grid_search
    predictions = model_fitted.predict(start=self.df_val.index[0], end=self.df_val.index[-1])
                                                                    ^^^^^^^^^^^
NameError: name 'y_train_len' is not defined
2024-08-19 11:46:52,812 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 11:46:52,827 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5256, Validação: 1752, Teste: 1752.
2024-08-19 11:46:52,830 - INFO - Dados escalonados para o intervalo: (-1, 1).
2024-08-19 11:46:52,830 - INFO - ARIMA_Model instanciado.
2024-08-19 11:46:52,830 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:52,831 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:52,832 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:53,261 - INFO - ARIMA(p=1, d=1, q=1) - MSE: 0.4960
2024-08-19 11:46:53,261 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:53,262 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:53,262 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:53,796 - INFO - ARIMA(p=1, d=1, q=2) - MSE: 0.4507
2024-08-19 11:46:53,797 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:53,797 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:53,798 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:56,924 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:46:57,087 - INFO - ARIMA(p=1, d=1, q=3) - MSE: 0.3037
2024-08-19 11:46:57,087 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:57,088 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:46:57,089 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:00,904 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:47:01,092 - INFO - ARIMA(p=1, d=1, q=4) - MSE: 0.3037
2024-08-19 11:47:01,093 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:01,093 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:01,094 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:01,793 - INFO - ARIMA(p=2, d=1, q=1) - MSE: 0.4806
2024-08-19 11:47:01,793 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:01,794 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:01,794 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:03,099 - INFO - ARIMA(p=2, d=1, q=2) - MSE: 0.3035
2024-08-19 11:47:03,099 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:03,100 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:03,100 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:06,249 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:47:06,377 - INFO - ARIMA(p=2, d=1, q=3) - MSE: 0.3014
2024-08-19 11:47:06,377 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:06,378 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:06,378 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:09,931 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:47:10,074 - INFO - ARIMA(p=2, d=1, q=4) - MSE: 0.3020
2024-08-19 11:47:10,074 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:10,075 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:10,075 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:12,467 - INFO - ARIMA(p=3, d=1, q=1) - MSE: 0.3044
2024-08-19 11:47:12,468 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:12,468 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:12,469 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:12,471 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:47:12,471 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:47:15,319 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:47:15,437 - INFO - ARIMA(p=3, d=1, q=2) - MSE: 0.3089
2024-08-19 11:47:15,437 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:15,438 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:15,438 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:19,484 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:47:19,621 - INFO - ARIMA(p=3, d=1, q=3) - MSE: 0.3022
2024-08-19 11:47:19,621 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:19,621 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:19,622 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:24,268 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:47:24,412 - INFO - ARIMA(p=3, d=1, q=4) - MSE: 0.3017
2024-08-19 11:47:24,413 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:24,413 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:24,413 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:27,601 - INFO - ARIMA(p=4, d=1, q=1) - MSE: 0.3048
2024-08-19 11:47:27,601 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:27,602 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:27,603 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:27,606 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:47:27,606 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:47:31,568 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:47:31,727 - INFO - ARIMA(p=4, d=1, q=2) - MSE: 0.3048
2024-08-19 11:47:31,728 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:31,728 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:31,729 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:36,499 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:47:36,685 - INFO - ARIMA(p=4, d=1, q=3) - MSE: 0.3021
2024-08-19 11:47:36,685 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:36,686 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:36,686 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:40,953 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:47:41,120 - INFO - ARIMA(p=4, d=1, q=4) - MSE: 0.3020
2024-08-19 11:47:41,120 - INFO - Melhor modelo: ARIMA((4, 1, 4)) - MSE: inf
2024-08-19 11:47:41,123 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:41,123 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:41,124 - WARNING - No frequency information was provided, so inferred frequency h will be used. (Category: ValueWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py, Line: 473)
2024-08-19 11:47:41,128 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:47:41,128 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:47:47,105 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:55:08,359 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 11:55:08,370 - ERROR - Erro ao carregar dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv - name 'df' is not defined
2024-08-19 11:55:08,370 - ERROR - Erro no processo de modelagem: name 'df' is not defined
2024-08-19 11:55:45,705 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 11:55:45,721 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5256, Validação: 1752, Teste: 1752.
2024-08-19 11:55:45,723 - INFO - Dados escalonados para o intervalo: (-1, 1).
2024-08-19 11:55:45,723 - INFO - ARIMA_Model instanciado.
2024-08-19 11:55:46,158 - INFO - ARIMA(p=1, d=1, q=1) - MSE: 0.4960
2024-08-19 11:55:46,697 - INFO - ARIMA(p=1, d=1, q=2) - MSE: 0.4507
2024-08-19 11:55:49,840 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:55:49,997 - INFO - ARIMA(p=1, d=1, q=3) - MSE: 0.3037
2024-08-19 11:55:53,853 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:55:54,044 - INFO - ARIMA(p=1, d=1, q=4) - MSE: 0.3037
2024-08-19 11:55:54,747 - INFO - ARIMA(p=2, d=1, q=1) - MSE: 0.4806
2024-08-19 11:55:56,041 - INFO - ARIMA(p=2, d=1, q=2) - MSE: 0.3035
2024-08-19 11:55:59,165 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:55:59,292 - INFO - ARIMA(p=2, d=1, q=3) - MSE: 0.3014
2024-08-19 11:56:02,850 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:56:02,997 - INFO - ARIMA(p=2, d=1, q=4) - MSE: 0.3020
2024-08-19 11:56:05,378 - INFO - ARIMA(p=3, d=1, q=1) - MSE: 0.3044
2024-08-19 11:56:05,381 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:56:05,381 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:56:08,234 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:56:08,358 - INFO - ARIMA(p=3, d=1, q=2) - MSE: 0.3089
2024-08-19 11:56:12,254 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:56:12,390 - INFO - ARIMA(p=3, d=1, q=3) - MSE: 0.3022
2024-08-19 11:56:16,974 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:56:17,130 - INFO - ARIMA(p=3, d=1, q=4) - MSE: 0.3017
2024-08-19 11:56:20,207 - INFO - ARIMA(p=4, d=1, q=1) - MSE: 0.3048
2024-08-19 11:56:20,210 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 11:56:20,210 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 11:56:24,214 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:56:24,383 - INFO - ARIMA(p=4, d=1, q=2) - MSE: 0.3048
2024-08-19 11:56:28,992 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:56:29,189 - INFO - ARIMA(p=4, d=1, q=3) - MSE: 0.3021
2024-08-19 11:56:33,535 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 11:56:33,699 - INFO - ARIMA(p=4, d=1, q=4) - MSE: 0.3020
2024-08-19 11:56:33,699 - INFO - Melhor modelo: ARIMA((2, 1, 3)) - MSE: 0.3014
2024-08-19 11:56:37,601 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:11,845 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 13:09:11,865 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5256, Validação: 1752, Teste: 1752.
2024-08-19 13:09:11,872 - INFO - Dados escalonados para o intervalo: (-1, 1).
2024-08-19 13:09:11,872 - INFO - ARIMA_Model instanciado.
2024-08-19 13:09:12,318 - INFO - ARIMA(p=1, d=1, q=1) - MSE: 0.4960
2024-08-19 13:09:12,874 - INFO - ARIMA(p=1, d=1, q=2) - MSE: 0.4507
2024-08-19 13:09:16,088 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:16,245 - INFO - ARIMA(p=1, d=1, q=3) - MSE: 0.3037
2024-08-19 13:09:20,234 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:20,433 - INFO - ARIMA(p=1, d=1, q=4) - MSE: 0.3037
2024-08-19 13:09:21,191 - INFO - ARIMA(p=2, d=1, q=1) - MSE: 0.4806
2024-08-19 13:09:22,562 - INFO - ARIMA(p=2, d=1, q=2) - MSE: 0.3035
2024-08-19 13:09:25,883 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:26,007 - INFO - ARIMA(p=2, d=1, q=3) - MSE: 0.3014
2024-08-19 13:09:29,636 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:29,787 - INFO - ARIMA(p=2, d=1, q=4) - MSE: 0.3020
2024-08-19 13:09:32,318 - INFO - ARIMA(p=3, d=1, q=1) - MSE: 0.3044
2024-08-19 13:09:32,321 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:09:32,322 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:09:35,342 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:35,459 - INFO - ARIMA(p=3, d=1, q=2) - MSE: 0.3089
2024-08-19 13:09:39,615 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:39,753 - INFO - ARIMA(p=3, d=1, q=3) - MSE: 0.3022
2024-08-19 13:09:44,441 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:44,601 - INFO - ARIMA(p=3, d=1, q=4) - MSE: 0.3017
2024-08-19 13:09:47,761 - INFO - ARIMA(p=4, d=1, q=1) - MSE: 0.3048
2024-08-19 13:09:47,765 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:09:47,765 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:09:51,770 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:51,944 - INFO - ARIMA(p=4, d=1, q=2) - MSE: 0.3048
2024-08-19 13:09:56,653 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:09:56,856 - INFO - ARIMA(p=4, d=1, q=3) - MSE: 0.3021
2024-08-19 13:10:01,171 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:10:01,337 - INFO - ARIMA(p=4, d=1, q=4) - MSE: 0.3020
2024-08-19 13:10:01,337 - INFO - Melhor modelo: ARIMA((2, 1, 3)) - MSE: 0.3014
2024-08-19 13:10:05,087 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:12:32,050 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 13:17:11,255 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 13:17:52,923 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 13:18:32,062 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 13:29:45,276 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 13:29:45,292 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5256, Validação: 1752, Teste: 1752.
2024-08-19 13:29:45,294 - INFO - Dados escalonados para o intervalo: (-1, 1).
2024-08-19 13:29:45,294 - INFO - ARIMA_Model instanciado.
2024-08-19 13:29:45,294 - INFO - Executando GridSearch.
2024-08-19 13:29:45,735 - INFO - ARIMA(p=1, d=1, q=1) - MSE: 0.4960
2024-08-19 13:29:46,288 - INFO - ARIMA(p=1, d=1, q=2) - MSE: 0.4507
2024-08-19 13:29:49,494 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:29:49,652 - INFO - ARIMA(p=1, d=1, q=3) - MSE: 0.3037
2024-08-19 13:29:53,565 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:29:53,756 - INFO - ARIMA(p=1, d=1, q=4) - MSE: 0.3037
2024-08-19 13:29:54,469 - INFO - ARIMA(p=2, d=1, q=1) - MSE: 0.4806
2024-08-19 13:29:55,814 - INFO - ARIMA(p=2, d=1, q=2) - MSE: 0.3035
2024-08-19 13:29:59,083 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:29:59,215 - INFO - ARIMA(p=2, d=1, q=3) - MSE: 0.3014
2024-08-19 13:30:02,847 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:30:03,013 - INFO - ARIMA(p=2, d=1, q=4) - MSE: 0.3020
2024-08-19 13:30:05,477 - INFO - ARIMA(p=3, d=1, q=1) - MSE: 0.3044
2024-08-19 13:30:05,480 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:30:05,480 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:30:08,337 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:30:08,455 - INFO - ARIMA(p=3, d=1, q=2) - MSE: 0.3089
2024-08-19 13:30:12,389 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:30:12,523 - INFO - ARIMA(p=3, d=1, q=3) - MSE: 0.3022
2024-08-19 13:30:17,065 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:30:17,225 - INFO - ARIMA(p=3, d=1, q=4) - MSE: 0.3017
2024-08-19 13:30:20,314 - INFO - ARIMA(p=4, d=1, q=1) - MSE: 0.3048
2024-08-19 13:30:20,317 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:30:20,317 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:30:24,210 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:30:24,377 - INFO - ARIMA(p=4, d=1, q=2) - MSE: 0.3048
2024-08-19 13:30:29,015 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:30:29,220 - INFO - ARIMA(p=4, d=1, q=3) - MSE: 0.3021
2024-08-19 13:30:33,498 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:30:33,662 - INFO - ARIMA(p=4, d=1, q=4) - MSE: 0.3020
2024-08-19 13:30:33,662 - INFO - Melhor modelo encontrado: ARIMA((2, 1, 3)) - MSE: 0.3014
2024-08-19 13:30:33,662 - INFO - Ajustando e realizando previsões com o modelo ARIMA.
2024-08-19 13:30:37,335 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:30:37,483 - INFO - Calculando resíduos dos conjuntos de dados.
2024-08-19 13:43:01,527 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 13:43:36,036 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 13:48:23,355 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 13:48:25,987 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 13:50:06,875 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 13:50:29,513 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 13:50:30,710 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 13:50:31,214 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 13:50:35,782 - WARNING - Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]` (Category: FutureWarning, File: /var/lib/snapd/snap/pycharm-community/403/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py, Line: 709)
2024-08-19 13:50:43,605 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 13:50:43,620 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5255, Validação: 1752, Teste: 1752.
2024-08-19 13:50:43,622 - INFO - Dados escalonados para o intervalo: (-1, 1).
2024-08-19 13:50:43,622 - INFO - ARIMA_Model instanciado.
2024-08-19 13:50:43,622 - INFO - Executando GridSearch.
2024-08-19 13:50:44,973 - INFO - ARIMA(p=1, d=1, q=1) - MSE: 0.0241
2024-08-19 13:50:47,668 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:50:47,802 - INFO - ARIMA(p=1, d=1, q=2) - MSE: 0.0241
2024-08-19 13:50:51,119 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:50:51,269 - INFO - ARIMA(p=1, d=1, q=3) - MSE: 0.0241
2024-08-19 13:50:55,044 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:50:55,213 - INFO - ARIMA(p=1, d=1, q=4) - MSE: 0.0241
2024-08-19 13:50:57,204 - INFO - ARIMA(p=2, d=1, q=1) - MSE: 0.0241
2024-08-19 13:51:00,971 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:51:01,102 - INFO - ARIMA(p=2, d=1, q=2) - MSE: 0.0241
2024-08-19 13:51:01,105 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:51:01,105 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:51:04,655 - INFO - ARIMA(p=2, d=1, q=3) - MSE: 0.0241
2024-08-19 13:51:04,659 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:51:09,123 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:51:09,330 - INFO - ARIMA(p=2, d=1, q=4) - MSE: 0.0241
2024-08-19 13:51:12,586 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:51:12,726 - INFO - ARIMA(p=3, d=1, q=1) - MSE: 0.0241
2024-08-19 13:51:12,729 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:51:12,729 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:51:16,225 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:51:16,380 - INFO - ARIMA(p=3, d=1, q=2) - MSE: 0.0241
2024-08-19 13:51:16,383 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:51:16,384 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:51:20,186 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:51:20,382 - INFO - ARIMA(p=3, d=1, q=3) - MSE: 0.0241
2024-08-19 13:51:20,386 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:51:24,600 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:51:24,801 - INFO - ARIMA(p=3, d=1, q=4) - MSE: 0.0278
2024-08-19 13:51:28,526 - INFO - ARIMA(p=4, d=1, q=1) - MSE: 0.0241
2024-08-19 13:51:28,529 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:51:28,530 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:51:32,003 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:51:32,178 - INFO - ARIMA(p=4, d=1, q=2) - MSE: 0.0241
2024-08-19 13:51:32,181 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:51:32,181 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:51:36,487 - INFO - ARIMA(p=4, d=1, q=3) - MSE: 0.0241
2024-08-19 13:51:36,492 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:51:41,395 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:51:41,579 - INFO - ARIMA(p=4, d=1, q=4) - MSE: 0.0241
2024-08-19 13:51:41,579 - INFO - Melhor modelo encontrado: ARIMA((2, 1, 4)) - MSE: 0.0241
2024-08-19 13:51:41,580 - INFO - Ajustando e realizando previsões com o modelo ARIMA.
2024-08-19 13:51:41,583 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:51:48,033 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:51:48,283 - INFO - Calculando resíduos dos conjuntos de dados.
2024-08-19 13:54:19,277 - INFO - Carregando dados do arquivo: DATASET2023-INPUT/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023_processed.csv
2024-08-19 13:54:19,292 - INFO - Tamanho dos conjuntos de dados: Treinamento: 5241, Validação: 1747, Teste: 1748.
2024-08-19 13:54:19,295 - INFO - Dados escalonados para o intervalo: (-1, 1).
2024-08-19 13:54:19,295 - INFO - ARIMA_Model instanciado.
2024-08-19 13:54:19,295 - INFO - Executando GridSearch.
2024-08-19 13:54:19,313 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:54:20,998 - INFO - ARIMA(p=1, d=1, q=1) - MSE: 0.0146
2024-08-19 13:54:23,149 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:54:23,279 - INFO - ARIMA(p=1, d=1, q=2) - MSE: 0.0146
2024-08-19 13:54:26,335 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:54:26,491 - INFO - ARIMA(p=1, d=1, q=3) - MSE: 0.0146
2024-08-19 13:54:30,647 - INFO - ARIMA(p=1, d=1, q=4) - MSE: 0.0146
2024-08-19 13:54:32,627 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:54:32,749 - INFO - ARIMA(p=2, d=1, q=1) - MSE: 0.0146
2024-08-19 13:54:35,883 - INFO - ARIMA(p=2, d=1, q=2) - MSE: 0.0146
2024-08-19 13:54:39,229 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:54:39,398 - INFO - ARIMA(p=2, d=1, q=3) - MSE: 0.0146
2024-08-19 13:54:43,544 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:54:43,750 - INFO - ARIMA(p=2, d=1, q=4) - MSE: 0.0146
2024-08-19 13:54:46,292 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:54:46,432 - INFO - ARIMA(p=3, d=1, q=1) - MSE: 0.0146
2024-08-19 13:54:49,870 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:54:50,021 - INFO - ARIMA(p=3, d=1, q=2) - MSE: 0.0146
2024-08-19 13:54:53,967 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:54:54,154 - INFO - ARIMA(p=3, d=1, q=3) - MSE: 0.0146
2024-08-19 13:54:58,789 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:54:59,005 - INFO - ARIMA(p=3, d=1, q=4) - MSE: 0.0146
2024-08-19 13:55:02,771 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:55:02,944 - INFO - ARIMA(p=4, d=1, q=1) - MSE: 0.0146
2024-08-19 13:55:02,947 - WARNING - Non-stationary starting autoregressive parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 966)
2024-08-19 13:55:02,948 - WARNING - Non-invertible starting MA parameters found. Using zeros as starting parameters. (Category: UserWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/tsa/statespace/sarimax.py, Line: 978)
2024-08-19 13:55:06,299 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:55:06,488 - INFO - ARIMA(p=4, d=1, q=2) - MSE: 0.0146
2024-08-19 13:55:11,631 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:55:11,825 - INFO - ARIMA(p=4, d=1, q=3) - MSE: 0.0146
2024-08-19 13:55:18,113 - WARNING - Maximum Likelihood optimization failed to converge. Check mle_retvals (Category: ConvergenceWarning, File: /home/tathiana/miniconda3/lib/python3.12/site-packages/statsmodels/base/model.py, Line: 607)
2024-08-19 13:55:18,359 - INFO - ARIMA(p=4, d=1, q=4) - MSE: 0.0146
2024-08-19 13:55:18,359 - INFO - Melhor modelo encontrado: ARIMA((3, 1, 2)) - MSE: 0.0146
2024-08-19 13:55:18,360 - INFO - Ajustando e realizando previsões com o modelo ARIMA.
2024-08-19 13:55:23,015 - INFO - Calculando resíduos dos conjuntos de dados.
